version: "2.2"

services:
  node:
    image: rchain/rnode:dev
    volumes:
      - ./data/:/data
    network_mode: "host"
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - BOOTSTRAP=${BOOTSTRAP}
    command: run --data_dir /data --bonds-file /data/bonds.txt --validator-private-key ${PRIVATE_KEY} --bootstrap ${BOOTSTRAP}
