version: "2.2"

services:
  node:
    image: rchain/rnode:testing
    network_mode: "host"
    volumes:
      - ./data/:/data
      - ./src/:/opt/docker/src
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - BOOTSTRAP=${BOOTSTRAP}
    command: run --data_dir /data --default-timeout 6000 --validator-private-key ${PRIVATE_KEY} -b ${BOOTSTRAP}
